# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 593534bd631729dabd0d981ecfb515e53395cf7741b0bc5d80042c70f7c2656b4b38c84f380031ddb27b79354e2f075c37b7d44ffbae59dbf02ae5dbed32b2a6

test:
  secret_key_base: 4ee4d3f08bac23be556190851caaba02d56b7a150f90cb42e5d190c8044d1002bea0a53e9eb73127ffe16c5a190eb1e9d5ade0d300c5939b60baa56b03690674

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
